### ISSUE TITLE
webkitRequestFullscreen makes keyboard invisible

### ISSUE THREAD

**Issue by AutomationEngineer** [xontab/chrome-virtual-keyboard#12]
Hello!
It's cool application and works perfect! The only thing that makes me upset, is the fact it doesn't show up when I use document.getElementById('fs').webkitRequestFullscreen() in chrome.

Live example is at:
https://bl.ocks.org/AutomationEngineer/raw/203b24d38ddfd0825ea6c65cdafa6eb2/

It would be great if its possible for you to fix this, or is there a workaround?

Regards,
Vicror

**Comment by AutomationEngineer** [comment]
I have fixed this in my fork and have created a pull request to your master  #13   . Please see if it would be possible to merge.
PS: I believe removeChild is not nesessary

**Comment by xontab** [comment]
Thanks a lot.  Merged your pull request
